%% file Names must be specified in lines (6),35,56,60!

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: M:\Studium\Projektarbeit\Ressourcen\Input_Dateien\E210.dat
%
% Auto-generated by MATLAB on 17-Jul-2022 12:03:23

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "Var3"];
opts.SelectedVariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var3", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "VarName1", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName1", "ThousandsSeparator", ",");

% Import the data
tbl = readtable("M:\Studium\Projektarbeit\Ressourcen\Input_Dateien\E210.dat", opts);

%% Convert to output type
xVal = tbl.VarName1;
zVal = tbl.VarName2;

%% Clear temporary variables
clear opts tbl


%% write data to string
xStr = num2str(xVal(1,1));
yStr = num2str(0.0);
zStr = num2str(zVal(1,1));
for i=2:150
    xStr = append(xStr,";",num2str(xVal(i,1)));
    yStr = append(yStr,";",num2str(0.0));
    zStr = append(zStr,";",num2str(zVal(i,1)));

end

%% write strings to file

fid = fopen('E210.cpacs.x.dat','wt');
fprintf(fid,'%s',xStr);
fclose(fid);

fid = fopen('E210.cpacs.y.dat','wt');
fprintf(fid,'%s',yStr);
fclose(fid);

fid = fopen('E210.cpacs.z.dat','wt');
fprintf(fid,'%s',zStr);
fclose(fid);

clear;